;;; lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from claude-collab.el

(register-definition-prefixes "claude-collab" '("claude-collab-"))


;;; Generated autoloads from claude-collab-core.el

(register-definition-prefixes "claude-collab-core" '("claude-collab-core-"))


;;; Generated autoloads from claude-collab-core-test.el

(register-definition-prefixes "claude-collab-core-test" '("claude-collab-core-test--anchor"))


;;; Generated autoloads from claude-collab-test.el

(register-definition-prefixes "claude-collab-test" '("claude-collab-"))


;;; Generated autoloads from menubar-export.el

(register-definition-prefixes "menubar-export" '("my/menubar-"))


;;; Generated autoloads from monday-docs-sync.el

(autoload 'monday-docs-sync-abort "monday-docs-sync" "\
Stop a running `monday-docs-sync' at the next step boundary.

Sets the abort flag, kills any in-flight curl/plantuml subprocesses,
and clears the in-flight marker so a new sync can start immediately." t)
(autoload 'monday-docs-sync "monday-docs-sync" "\
Sync the current org buffer to the Monday doc in its `#+MONDAY_DOC:' keyword.

Whole-doc replace: deletes every existing block in the target doc,
prepends a read-only notice, then writes the converted blocks.  The
HTTP pipeline is truly async — each curl runs via
`make-process' + sentinel; Emacs never blocks.  Progress is reported
via `message'.

Diagrams are re-rendered on the main thread (when
`monday-docs-sync-force-render' is non-nil) before the pipeline kicks
off — org-babel isn't thread-safe." t)
(register-definition-prefixes "monday-docs-sync" '("monday-docs-sync-"))


;;; Generated autoloads from user-config.el

(register-definition-prefixes "user-config" '("my/"))

;;; End of scraped data

(provide 'lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lisp-autoloads.el ends here
